### ISSUE TITLE
Local repo usage

### ISSUE THREAD

**Issue by muliyul** [git-as-svn/git-lfs-java#110]
My use case involves working against a local git repo.

Is this supported by the client module? How can I proceed?

**Comment by slonopotamus** [comment]
I'm not sure what you mean by "local git repo" git-lfs-java implements [git-lfs protocol](https://github.com/git-lfs/git-lfs/tree/main/docs/api). You can use it to talk to remote git-lfs repo or you can use it to create your own git-lfs repo that other git-lfs compatible software can talk to.

**Comment by muliyul** [comment]
What I meant is I needed support for the `file://` scheme. This is no longer relevant for me but I'll leave this open for others.
