### ISSUE TITLE
Uploading to git-lfs on github fails

### ISSUE THREAD

**Issue by krishnanrajah** [git-as-svn/git-lfs-java#168]
Hi, 

Am using the gitlfs library to upload a file to git-lfs repo in github. The upload always returns false, upon debugging it looks like the response to /info/lfs/objects is coming as 200 and the response has the required _links object. But looks like MetaPost.processResponse is needing 202 as response. It returns null when the status code is 200. How can I solve this problem? Pls advise 

Thanks
Krishnan

**Comment by slonopotamus** [comment]
I want to note that this is a legacy protocol and the recommended approach is to use batch API.

**Comment by krishnanrajah** [comment]
The problem I see is the body has the _links object with the href etc.. so does it still mean the object is already uploaded? Also if I try to update a file with no changes I would get this problem?

**Comment by krishnanrajah** [comment]
> I believe this is expected behavior. According to the [spec](https://github.com/git-lfs/git-lfs/blob/main/docs/api/basic-transfers.md?plain=1#L144) . Spec example also shows that server responds with empty body.

I believe the 200 means "the object exists on the server" is for the verification url, not for the first action.

**Comment by slonopotamus** [comment]
> I believe the 200 means "the object exists on the server" is for the verification url, not for the first action.

Sorry, wrong line. This one is correct: https://github.com/git-lfs/git-lfs/blob/main/docs/api/basic-transfers.md?plain=1#L90


> The problem I see is the body has the _links object with the href etc

The spect only guarantees that server will return 200. We cannot rely on response body in any way. Other lfs server implementations can have it empty.

I'm not sure what exactly you're calling a problem. `putObject` either returns `true` if upload happened or `false` if it was unnecessary. In either case, if there were no exceptions, you can be sure that the file is now in server storage.

**Comment by krishnanrajah** [comment]
The code never reaches the putObject part , when the getLinks is called it returns null. The MetaPost.processResponse is returning null because the status code is 200. 

https://github.com/git-as-svn/git-lfs-java/blob/00183a9a52987ee69be7179950121e06de10f40a/gitlfs-client/src/main/kotlin/ru/bozaro/gitlfs/client/internal/MetaPost.kt#L35
